language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t singhankitin/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true singhankitin/frontend npm run test -- --coverage
